
# tasks file for grafana-server
---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install prerequisite packages
  ansible.builtin.apt:
    name: apt-transport-https
    state: present

- name: Import Grafana GPG key
  ansible.builtin.apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present

- name: Add Grafana APT repository
  ansible.builtin.apt_repository:
    repo: "deb https://packages.grafana.com/oss/deb stable main"
    state: present
    update_cache: yes

- name: Install Grafana
  ansible.builtin.apt:
    name: grafana
    state: present

- name: Start and enable Grafana service
  ansible.builtin.systemd:
    name: grafana-server
    state: started
    enabled: yes

- name: Check if Grafana is accessible
  ansible.builtin.uri:
    url: http://127.0.0.1:3000
    status_code: 200
